require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rake
  - rubocop-thread_safety

AllCops:
  NewCops: enable
  Exclude:
    - bin/**/*
    - db/**/*
    - vendor/**/*

# Disable block length metric for ActiveAdmin files and environment files and routes file
Metrics/BlockLength:
  Exclude:
    - app/admin/**/*
    - config/environments/**/*
    - config/routes.rb

# Allow to use join table only without other attributes
Rails/HasAndBelongsToMany:
  Enabled: false

# The exceptions class already explain its purpose, so disable the top level documentation for them
# Parameter validator names also already self explanatory
Style/Documentation:
  Exclude:
    - config/application.rb
    - app/**/application_*
    - app/models/param_validations/**/*
    - app/helpers/**/*
    - app/channels/**/*
    - lib/exceptions/**/*

# All of services may override the constructor, we don't want to specify super everytime there
# becuase there is no super implementation
Lint/MissingSuper:
  Exclude:
    - app/services/**/*

# The services uses *args on the super, so it seems to be not working with optional parameter.
# TODO: this should be removed!
Style/OptionalBooleanParameter:
  Exclude:
    - app/services/**/*
